-- AC4：20 个互不相同的学生账号，密码与 stu01 相同（123456）
USE venue_booking;

INSERT INTO `user` (`username`, `password_hash`, `role`, `status`)
SELECT CONCAT('stress', seq.n), u.password_hash, 'STUDENT', 'ACTIVE'
FROM `user` u
JOIN (
  SELECT 1 AS n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5
  UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10
  UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15
  UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20
) seq
WHERE u.username = 'stu01'
  AND NOT EXISTS (SELECT 1 FROM `user` x WHERE x.username = CONCAT('stress', seq.n));
